# -*- coding: utf-8 -*-
"""md5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4BMCBzgUMCl33ZkD-QEPOTYDBe4uWWY
"""

import hashlib

def md5_hash(input_string):
    # Encode the input string to bytes
    input_bytes = input_string.encode('utf-8')

    # Compute the MD5 hash
    md5_hash = hashlib.md5(input_bytes)

    # Return the hexadecimal representation of the hash
    return md5_hash.hexdigest()

# Example usage:
input_string = "Hello, World!"
hashed_value = md5_hash(input_string)
print("MD5 hash of '{}' is: {}".format(input_string, hashed_value))